# Generated by Django 4.1.2 on 2022-11-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ciphers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciphers",
            name="title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
